spring:
  application.name: user-service
server.port: ${SERVER_PORT:8082}
service.url: ${SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include: health,info
springdoc.swagger-ui.path: /swagger-ui.html
spring.datasource.url: ${DB_URL}
spring.datasource.username: ${DB_USERNAME}
spring.datasource.password: ${DB_PASSWORD}
logging.level.com.atm: ${LOG_LEVEL:INFO}
