package com.atm.common.event;

public enum EventType {
    ATM_CREATED,
    ATM_UPDATED,
    TRANSACTION_CREATED,
    CASH_UPDATED,
    REFILL_REQUESTED,
    REFILL_COMPLETED,
    PREDICTION_GENERATED,
    LOW_CASH_DETECTED,
    STOCKOUT_RISK_DETECTED,
    ALERT_GENERATED,
    RECOMMENDATION_CREATED
}