spring:
  application.name: config-server
server.port: ${SERVER_PORT:8888}
service.url: ${SERVICE_URL:http://localhost:8888}
management.endpoints.web.exposure.include: health,info
logging.level.com.atm: ${LOG_LEVEL:INFO}
